---
- name: Setup dev machine (system)
  hosts: dev_machines
  become: yes
  debugger: on_failed
  module_defaults:
    copy:
      backup: yes
    lineinfile:
      backup: yes
    xml:
      backup: yes

  tasks:
    - include_role:
        name: system

- name: Setup dev machine (user)
  hosts: dev_machines
  vars:
    user: "{{ ansible_facts['user_id'] }}"

  tasks:
    - include_role:
        name: user
