---
- name: Setup dev machine (system)
  hosts: dev_machines
  become: yes
  debugger: on_failed
  module_defaults:
    copy:
      backup: yes
    lineinfile:
      backup: yes
    xml:
      backup: yes

  tasks:
    - name: Update packages
      apt:
        cache_valid_time: 86400 # one day
        upgrade: dist
    - include_role:
        name: system
    - name: Cleanup packages
      apt:
        autoclean: yes
        autoremove: yes

- name: Setup dev machine (user)
  hosts: dev_machines
  vars:
    user: "{{ ansible_facts['user_id'] }}"

  tasks:
    - include_role:
        name: user
