---
- name: setup laptop
  hosts: localhost

  tasks:
    - name: Update packages
      become: yes
      become_method: sudo
      apt:
        cache_valid_time: 86400 # one day
        upgrade: dist

    - name: Install editors
      become: yes
      become_method: sudo
      apt:
        name:
          - vim-gtk3
    - name: Install system hardware tools
      become: yes
      become_method: sudo
      apt:
        name:
          - acpi-call-dkms
          - tlp
    - name: Install system tools
      become: yes
      become_method: sudo
      apt:
        name:
          - ca-certificates
          - apt-transport-https
          - cifs-utils
          - htop
          - powertop
          - python3-pip
          - python3-venv
          - tmux
          - wine-stable
    - name: Install network tools
      become: yes
      become_method: sudo
      apt:
        name:
          - curl
          - net-tools
          - bridge-utils
          - wavemon
    - name: Install git
      become: yes
      become_method: sudo
      apt:
        name:
          - git
          - gitk
          - git-gui
          - git-flow
          - kdiff3
    - name: Install build tools
      become: yes
      become_method: sudo
      apt:
        name:
          - build-essential
          - automake
          - autoconf
          - libtool
          - pkg-config
    - name: Install programming tools
      become: yes
      become_method: sudo
      apt:
        name:
          - postgresql-client
        #   - pgadmin3
        #   - python3-pip
          - python3-venv
          - fonts-firacode

    - name: Install user application
      become: yes
      become_method: sudo
      apt:
        name:
          - chromium-browser
          - yakuake
          - xsane
          - plasma-applet-redshift-control
          - okteta

    - name: Add Docker apt key
      become: yes
      become_method: sudo
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker repo
      become: yes
      become_method: sudo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    - name: Install Docker
      become: yes
      become_method: sudo
      apt:
        name: docker-ce
    - name: Grant user privs to docker
      become: yes
      become_method: sudo
      user:
        name: basicdays
        append: yes
        groups: docker
    - name: Install docker-compose for user
      pip:
        extra_args: --user --upgrade
        name: docker-compose

    - name: Add VirtualBox apt key
      become: yes
      become_method: sudo
      apt_key:
        id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - name: Add VirtualBox repo
      become: yes
      become_method: sudo
      apt_repository:
        repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
    - name: Install VirtualBox
      become: yes
      become_method: sudo
      apt:
        name: virtualbox-6.1
    - name: Grant user privs to VirtualBox
      become: yes
      become_method: sudo
      user:
        name: basicdays
        append: yes
        groups: vboxusers

    - name: Install Python applications for user
      pip:
        extra_args: --user --upgrade
        name:
          - ansible
          - awscli
          - awsebcli
          - pip
          - powerline-status
          - virtualenv
          - ansible-lint

    - name: Add Spotify apt key
      become: yes
      become_method: sudo
      apt_key:
        id: 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45
        url: https://download.spotify.com/debian/pubkey.gpg
    - name: Add Spotify repo
      become: yes
      become_method: sudo
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
    - name: Install Spotify
      become: yes
      become_method: sudo
      apt:
        name: spotify-client

    - name: Cleanup packages
      become: yes
      become_method: sudo
      apt:
        autoclean: yes
        autoremove: yes
