- name: Install Python applications for user
  pip:
    extra_args: --user
    name:
      - ansible
      - awscli
      - awsebcli
      - docker-compose
      - pip
      - poetry
      - powerline-status
      - ansible-lint
