- name: Modify privs
  block:
  - name: Secure user home directory
    file:
      path: "{{ ansible_facts['user_dir'] }}"
      mode: o-rx
  - name: Grant user privs to applications
    become: yes
    user:
      name: "{{ user }}"
      append: yes
      groups:
        - docker
        - vboxusers
        - wireshark
