galaxy_info:
  author: BasicDays
  description: System installation
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: ArchLinux
      versions:
        - all

dependencies:
  - role: kewlfft.aur
