- name: Install Docker
  block:
    - name: Add Docker pre-reqs
      apt:
        name: apt-transport-https
    - name: Add Docker repo key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable
    - name: Install Docker
      apt:
        name: docker-ce
