- include_tasks: update.yaml

# Install any packages required by Ansible modules
- include_tasks: ansible-pre-reqs.yaml

- name: Arch Packages
  block:
    - include_tasks: arch-packages.yaml
  when: ansible_facts['os_family'] is ArchLinux

- name: Ubuntu Packages
  block:
    # Install packages
    - include_tasks: ubuntu-packages.yaml
  when: ansible_facts['os_family'] is Debian

- include_tasks: docker.yaml
- include_tasks: nodejs.yaml
- include_tasks: virtual-box.yaml
- include_tasks: vscode.yaml

# Modify configuration files
- include_tasks: etc.yaml
# note: not very useful as it doesn't include IP addresses
# - include_tasks: known-hosts.yaml

- include_tasks: "cleanup.yaml"
