- name: Install Node.js (Ubuntu)
  block:
    - name: Install Node.js (official)
      block:
        - name: Add Node.js pre-reqs
          apt:
            name: apt-transport-https
        - name: Add Node.js repo key
          apt_key:
            id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
            url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        - name: Add Node.js repo
          apt_repository:
            filename: nodejs
            repo: deb https://deb.nodesource.com/node_14.x {{ ansible_facts['distribution_release'] }} main
        - name: Install Node.js (official)
          apt:
            name: nodejs

    - name: Install Yarn (official)
      block:
        - name: Add Yarn repo key
          apt_key:
            id: 72ECF46A56B4AD39C907BBB71646B01B86E50310
            url: https://dl.yarnpkg.com/debian/pubkey.gpg
        - name: Add Yarn repo
          apt_repository:
            filename: yarn
            repo: deb https://dl.yarnpkg.com/debian/ stable main
        - name: Install Yarn (official)
          apt:
            name: yarn
  when: ansible_facts['os_family'] is Debian
