- name: Install Ubuntu packages
  block:
    - name: Set Wireshark to use group privs
      debconf:
        name: wireshark-common
        question: wireshark-common/install-setuid
        vtype: boolean
        value: "true"
    - name: Install Ubuntu packages
      apt:
        name:
          # editors
          - vim-gtk3

          # hardware
          - acpi-call-dkms
          - tlp

          # file system tools
          - cifs-utils

          # system tools
          - htop
          - imagemagick
          - mesa-utils
          - powertop
          - tmux
          # - usb-creator-kde
          - wine-stable

          # network tools
          - curl
          - fail2ban
          # - net-tools
          # - bridge-utils
          # - wavemon
          - openssh-server
          - wireshark

          # git
          - git
          - gitk
          - git-flow
          - git-gui
          - kdiff3

          # building
          - autoconf
          - automake
          - build-essential
          - cmake
          - gettext
          - libtool
          - m4
          - pkg-config

          # amethyst dependencies (https://github.com/amethyst/amethyst#dependencies)
          - build-essential
          - cmake
          - libasound2-dev
          - libexpat1-dev
          # Is this still needed? not official dep, but fixed font errors
          - libfontconfig1-dev
          - libfreetype6-dev
          - libssl-dev
          - libx11-dev
          - libxcb-composite0-dev
          - openssl
          - pkg-config
          - python3

          # programming
          - fonts-firacode
          # - pgadmin3
          # - postgresql-client
          - python3-pip
          - python3-venv

          # applications
          # - calibre
          - filelight
          - gimp
          - inkscape
          - k3b
          - kamoso
          - kate
          - kcalc
          - kdf
          - kgpg
          - kmail
          # - kmarkdownwebview
          - kontact
          - korganizer
          - krdc
          - ksystemlog
          - ktorrent
          - libreoffice
          - obs-studio
          - partitionmanager
          - pavucontrol
          - okteta
          - pulseaudio-module-gsettings # 20.04 only?
          - sweeper
          - yakuake
          - xsane

          # games
          - prboom-plus
          - steam

    - name: Install Slack (snap classic)
      snap:
        name: slack
        classic: yes

    - name: Install Chromium (apt)
      apt:
        name: chromium-browser
      when: ansible_facts['distribution_version'] is version('20.04', '<')
    - name: Install Chromium (snap)
      snap:
        name: chromium
      when: ansible_facts['distribution_version'] is version('20.04', '>=')

    - name: Install snap applications
      snap:
        name:
          - discord
          - postman
          - spotify
          - telegram-desktop
