- name: Install Virtualbox (Ubuntu)
  block:
    - name: Install VirtualBox (official)
      block:
        - name: Add VirtualBox repo key
          apt_key:
            id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
            url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        - name: Add VirtualBox repo
          apt_repository:
            filename: virtualbox
            repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_facts['distribution_release'] }} contrib
        - name: Install VirtualBox (official)
          apt:
            name: virtualbox-6.1
      when: ansible_facts['distribution_version'] is version('20.04', '<')

    - name: Install VirtualBox (universal)
      block:
        - name: Set VirtualBox to accept license
          debconf:
            name: virtualbox-ext-pack
            question: virtualbox-ext-pack/license
            vtype: boolean
            value: "true"
        - name: Install VirtualBox (universal)
          apt:
            name:
              - virtualbox
              - virtualbox-dkms
              - virtualbox-ext-pack
              - virtualbox-guest-additions-iso
              - virtualbox-qt
      when: ansible_facts['distribution_version'] is version('20.04', '>=')
  when: ansible_facts['distribution'] is Ubuntu
