- name: Increase inotify limits
  copy:
    src: 15-local-inotify.conf
    dest: /etc/sysctl.d/
    mode: 0644
  notify: Reload notify limits

- name: Configure ssh
  block:
    - name: Configure ssh_config
      copy:
        src: ssh_config
        dest: /etc/ssh/
        mode: 0644
    - name: Enable COLORFGBG in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        backrefs: yes
        regexp: "^(?P<option>AcceptEnv (?:(?!COLORFGBG).)*)$"
        line: '\g<option> COLORFGBG'
    # - name: Disable hostname hashing in ssh_config
    #   lineinfile:
    #     path: /etc/ssh/ssh_config
    #     backrefs: yes
    #     regexp: '^#?(?P<option>\s*HashKnownHosts.*)'
    #     line: '#\g<option>'
    # - name: Enable COLORFGBG in ssh_config
    #   lineinfile:
    #     path: /etc/ssh/ssh_config
    #     backrefs: yes
    #     regexp: '^(?P<option>\s*SendEnv (?:(?!COLORFGBG).)*)$'
    #     line: '\g<option> COLORFGBG'

- name: Configure sudoers
  copy:
    # from ../files
    src: 10-local-sudoer
    dest: /etc/sudoers.d/
    validate: /usr/sbin/visudo -cf %s
    mode: 0440

- name: Configure TLP (Current)
  copy:
    src: 10-local-tlp.conf
    dest: /etc/tlp.d/
    mode: 0644
  notify: Restart tlp

- name: Configure ImageMagick
  block:
    - name: ImageMagick - Increase memory
      xml:
        path: /etc/ImageMagick-6/policy.xml
        xpath: /policymap/policy[@domain='resource' and @name='memory']
        attribute: value
        value: 1GiB
    - name: ImageMagick - Increase area memory
      xml:
        path: /etc/ImageMagick-6/policy.xml
        xpath: /policymap/policy[@domain='resource' and @name='area']
        attribute: value
        value: 1GB
    - name: ImageMagick - Enable PDF processing
      xml:
        path: /etc/ImageMagick-6/policy.xml
        xpath: /policymap/policy[@domain='coder' and @pattern='PDF']
        attribute: rights
        value: read|write
